parameters:
    sfynx.media.event_subscriber.media.class: Sfynx\MediaBundle\EventSubscriber\EventSubscriberMedia
    sfynx.media.provider.image.class: Sfynx\MediaBundle\Provider\ImageProvider
    sfynx.media.provider.file.class: Sfynx\MediaBundle\Provider\FileProvider
    sfynx.media.thumbnail.format.class: Sfynx\MediaBundle\Thumbnail\FormatThumbnail    
    
services:
    
    #
    # configuration of the forms
    #            
    sfynx_mediabundle_mediatype_file:
        class: Sfynx\MediaBundle\Form\MediaType
        arguments: ['@service_container', '@doctrine.orm.entity_manager', 'file' ]
        tags:
            - { name: form.type }      
            
    sfynx_mediabundle_mediatype_image:
        class: Sfynx\MediaBundle\Form\MediaType
        arguments: ['@service_container', '@doctrine.orm.entity_manager', 'image' ]
        tags:
            - { name: form.type }
            
    sfynx_mediabundle_mediatype_youtube:
        class: Sfynx\MediaBundle\Form\MediaType
        arguments: ['@service_container', '@doctrine.orm.entity_manager', 'youtube' ]
        tags:
            - { name: form.type }        
            
    sfynx_mediabundle_mediatype_dailymotion:
        class: Sfynx\MediaBundle\Form\MediaType
        arguments: ['@service_container', '@doctrine.orm.entity_manager', 'dailymotion' ]
        tags:
            - { name: form.type }   
            
    #
    # configuration of the event subscriber of entities
    #         
    sfynx.media.event_subscriber.media:
        class: %sfynx.media.event_subscriber.media.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }         
            
    #
    # configuration of the event subscriber surcharge
    #               
    sfynx.media.thumbnail.format:
      class: %sfynx.media.thumbnail.format.class%
      arguments: ['sfynx.media.provider.image']
            
    sfynx.media.provider.image:
      class: %sfynx.media.provider.image.class%
      arguments: ['sfynx.media.provider.image', '@sonata.media.filesystem.local', '@sonata.media.cdn.server', '@sonata.media.generator.default', '@sfynx.media.thumbnail.format', {}, {}, '@sonata.media.adapter.image.gd','@sonata.media.metadata.proxy']
      tags:
            - { name: sonata.media.provider }
      calls:
        - [ setTemplates, [ {'helper_thumbnail':'SonataMediaBundle:Provider:thumbnail.html.twig', 'helper_view':'SonataMediaBundle:Provider:view_file.html.twig'} ] ]             
            
    sfynx.media.provider.file:
      class: %sfynx.media.provider.file.class%
      arguments: ['sfynx.media.provider.file', '@sonata.media.filesystem.local', '@sonata.media.cdn.server', '@sonata.media.generator.default', '@sfynx.media.thumbnail.format', {}, {},'@sonata.media.metadata.proxy']
      tags:
            - { name: sonata.media.provider }
      calls:
        - [ setTemplates, [ {'helper_thumbnail':'SonataMediaBundle:Provider:thumbnail.html.twig', 'helper_view':'SonataMediaBundle:Provider:view_image.html.twig'} ] ]            
       